
services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=testShopper
      - DB_HOST=db
    volumes:
      - ./backend:/app-backend
    container_name: testShopper_backend
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always